<?php

/**
 * This is the model base class for the table "participante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Participante".
 *
 * Columns in table "participante" available as properties of the model,
 * followed by relations of table "participante" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombres
 * @property string $apellidos
 * @property string $tipo
 * @property string $telefono
 * @property string $email
 * @property string $direccion
 * @property integer $sector_id
 * @property integer $subsector_id
 * @property integer $rama_actividad_id
 * @property integer $actividad_id
 *
 * @property Sector $sector
 * @property Subsector $subsector
 * @property RamaActividad $ramaActividad
 * @property Actividad $actividad
 */
abstract class BaseParticipante extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'participante';
    }

    public static function representingColumn() {
        return 'nombres';
    }

    public function rules() {
        return array(
            array('nombres, apellidos, tipo, sector_id, subsector_id', 'required'),
            array('sector_id, subsector_id, rama_actividad_id, actividad_id', 'numerical', 'integerOnly'=>true),
            array('email', 'email'),
            array('nombres, apellidos', 'length', 'max'=>128),
            array('tipo', 'length', 'max'=>3),
            array('telefono, email', 'length', 'max'=>45),
            array('direccion', 'safe'),
            array('tipo', 'in', 'range' => array('N','E','CIA','COO','ASO')), // enum,
            array('telefono, email, direccion, rama_actividad_id, actividad_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombres, apellidos, tipo, telefono, email, direccion, sector_id, subsector_id, rama_actividad_id, actividad_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'sector' => array(self::BELONGS_TO, 'Sector', 'sector_id'),
            'subsector' => array(self::BELONGS_TO, 'Subsector', 'subsector_id'),
            'ramaActividad' => array(self::BELONGS_TO, 'RamaActividad', 'rama_actividad_id'),
            'actividad' => array(self::BELONGS_TO, 'Actividad', 'actividad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombres' => Yii::t('app', 'Nombres'),
                'apellidos' => Yii::t('app', 'Apellidos'),
                'tipo' => Yii::t('app', 'Tipo'),
                'telefono' => Yii::t('app', 'Telefono'),
                'email' => Yii::t('app', 'Email'),
                'direccion' => Yii::t('app', 'Direccion'),
                'sector_id' => Yii::t('app', 'Sector'),
                'subsector_id' => Yii::t('app', 'Subsector'),
                'rama_actividad_id' => Yii::t('app', 'Rama Actividad'),
                'actividad_id' => Yii::t('app', 'Actividad'),
                'sector' => null,
                'subsector' => null,
                'ramaActividad' => null,
                'actividad' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombres', $this->nombres, true);
        $criteria->compare('apellidos', $this->apellidos, true);
        $criteria->compare('tipo', $this->tipo, true);
        $criteria->compare('telefono', $this->telefono, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('direccion', $this->direccion, true);
        $criteria->compare('sector_id', $this->sector_id);
        $criteria->compare('subsector_id', $this->subsector_id);
        $criteria->compare('rama_actividad_id', $this->rama_actividad_id);
        $criteria->compare('actividad_id', $this->actividad_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}