<?php

/**
 * This is the model base class for the table "subsector".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Subsector".
 *
 * Columns in table "subsector" available as properties of the model,
 * followed by relations of table "subsector" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $estado
 * @property integer $sector_economico_id
 *
 * @property Participante[] $participantes
 * @property RamaActividad[] $ramaActividads
 * @property Sector $sectorEconomico
 */
abstract class BaseSubsector extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'subsector';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, estado, sector_economico_id', 'required'),
            array('sector_economico_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('id, nombre, estado, sector_economico_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'participantes' => array(self::HAS_MANY, 'Participante', 'subsector_id'),
            'ramaActividads' => array(self::HAS_MANY, 'RamaActividad', 'sector_detalle_id'),
            'sectorEconomico' => array(self::BELONGS_TO, 'Sector', 'sector_economico_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'estado' => Yii::t('app', 'Estado'),
                'sector_economico_id' => Yii::t('app', 'Sector Economico'),
                'participantes' => null,
                'ramaActividads' => null,
                'sectorEconomico' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('sector_economico_id', $this->sector_economico_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}