<?php

/**
 * This is the model base class for the table "participante_has_evento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ParticipanteHasEvento".
 *
 * Columns in table "participante_has_evento" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $participante_id
 * @property integer $evento_id
 *
 */
abstract class BaseParticipanteHasEvento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'participante_has_evento';
    }

    public static function representingColumn() {
        return array(
            'participante_id',
            'evento_id',
        );
    }

    public function rules() {
        return array(
            array('participante_id, evento_id', 'required'),
            array('participante_id, evento_id', 'numerical', 'integerOnly'=>true),
            array('participante_id, evento_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'participante_id' => Yii::t('app', 'Participante'),
                'evento_id' => Yii::t('app', 'Evento'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('participante_id', $this->participante_id);
        $criteria->compare('evento_id', $this->evento_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}