<?php

/**
 * This is the model base class for the table "actividad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Actividad".
 *
 * Columns in table "actividad" available as properties of the model,
 * followed by relations of table "actividad" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $estado
 * @property integer $rama_actividad_id
 *
 * @property RamaActividad $ramaActividad
 */
abstract class BaseActividad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'actividad';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, estado, rama_actividad_id', 'required'),
            array('rama_actividad_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>45),
            array('estado', 'length', 'max'=>8),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('id, nombre, estado, rama_actividad_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ramaActividad' => array(self::BELONGS_TO, 'RamaActividad', 'rama_actividad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'estado' => Yii::t('app', 'Estado'),
                'rama_actividad_id' => Yii::t('app', 'Rama Actividad'),
                'ramaActividad' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('rama_actividad_id', $this->rama_actividad_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}