<?php

/**
 * This is the model base class for the table "evento".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Evento".
 *
 * Columns in table "evento" available as properties of the model,
 * followed by relations of table "evento" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property string $fecha_inicio
 * @property string $fecha_fin
 * @property string $estado
 * @property string $descripcion
 *
 * @property Participante[] $participantes
 */
abstract class BaseEvento extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, fecha_inicio, estado', 'required'),
            array('nombre', 'length', 'max'=>128),
            array('estado', 'length', 'max'=>8),
            array('fecha_fin, descripcion', 'safe'),
            array('estado', 'in', 'range' => array('ACTIVO','INACTIVO')), // enum,
            array('fecha_fin, descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, fecha_inicio, fecha_fin, estado, descripcion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'participantes' => array(self::MANY_MANY, 'Participante', 'participante_has_evento(evento_id, participante_id)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'fecha_inicio' => Yii::t('app', 'Fecha Inicio'),
                'fecha_fin' => Yii::t('app', 'Fecha Fin'),
                'estado' => Yii::t('app', 'Estado'),
                'descripcion' => Yii::t('app', 'Descripcion'),
                'participantes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('fecha_inicio', $this->fecha_inicio, true);
        $criteria->compare('fecha_fin', $this->fecha_fin, true);
        $criteria->compare('estado', $this->estado, true);
        $criteria->compare('descripcion', $this->descripcion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}