<?php

/**
 * This is the model base class for the table "evento_participante".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EventoParticipante".
 *
 * Columns in table "evento_participante" available as properties of the model,
 * followed by relations of table "evento_participante" available as properties of the model.
 *
 * @property integer $evento_id
 * @property integer $participante_id
 *
 * @property Evento $evento
 * @property Participante $participante
 */
abstract class BaseEventoParticipante extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'evento_participante';
    }

    public static function representingColumn() {
        return 'evento_id';
    }

    public function rules() {
        return array(
            array('evento_id, participante_id', 'required'),
            array('evento_id, participante_id', 'numerical', 'integerOnly'=>true),
            array('evento_id, participante_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'evento' => array(self::BELONGS_TO, 'Evento', 'evento_id'),
            'participante' => array(self::BELONGS_TO, 'Participante', 'participante_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'evento_id' => Yii::t('app', 'Evento'),
                'participante_id' => Yii::t('app', 'Participante'),
                'evento' => null,
                'participante' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('evento_id', $this->evento_id);
        $criteria->compare('participante_id', $this->participante_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}